creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 3868B679AE3DA1A8E4A9DA553CFA81BA94ECB7E3
#    ,ANOTHER_FALSE_KEY_HERE
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: B17507C383ED1E1991E4CC816EF08F7317D626D2
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_FALSE_KEY_HERE
