apiVersion: v1
kind: Namespace
metadata:
  name: bigbang
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: environment-repo
  namespace: bigbang
spec:
  interval: 1m
  url: https://github.com/recarmona/template.git
  ref:
    branch: template-demo
  secretRef:
    name: private-git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: environment
  namespace: bigbang
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: environment-repo
  path: ./dev
  prune: true
<<<<<<< HEAD
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
=======
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-gpg
>>>>>>> 28c9109bc4920566404992a1bccd575d26851b33
