hostname: bigbang.dev

istio:
  enabled: false

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

istiooperator:
  # -- Toggle deployment of Istio Operator.
  enabled: true
  revision: "1-10-3"
  git:
    repo: https://github.com/danehans/istio-operator.git
    path: "./chart"
    tag: null
    branch: revision
#  canary:
#    revision: "1-10-3"
#    git:
#      repo: https://github.com/danehans/istio-operator.git
#      path: "./chart"
#      tag: null
#      branch: revision

gatekeeper:
  enabled: false
  values:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    violations:
      allowedDockerRegistries:
        match:
          excludedNamespaces:
          - kube-system
          - istio-system
          - default

kiali:
  enabled: false

jaeger:
  enabled: false

logging:
  enabled: false

fluentbit:
  enabled: false

clusterAuditor:
  enabled: false

monitoring:
  enabled: false

eckoperator:
  enabled: false

twistlock:
  enabled: false
