hostname: bigbang.dev

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

#istio:
#  enabled: true

#istios:
#  canary:
#    # -- Toggle deployment of Istio.
#    enabled: true
#    revision: 1-10-3
#    git:
#      repo: https://github.com/danehans/istio-controlplane.git
#      path: "./chart"
#      tag: null
#      branch: revision_support
#
#    # -- Flux reconciliation overrides specifically for the Istio Package
#    flux: {}
#
#    # -- Values to passthrough to the istio-controlplane chart: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane.git
#    values: {}
#
#    # -- Post Renderers.  See docs/postrenders.md
#    postRenderers: []

#istiooperators:
#  default:
#    enabled: true
#    git:
#      repo: https://github.com/danehans/istio-operator.git
#      path: "./chart"
#      tag: null
#      branch: revision
#  canary:
#    enabled: true
#    revision: 1-10-3
#    git:
#      repo: https://github.com/danehans/istio-operator.git
#      path: "./chart"
#      tag: null
#      branch: revision
    # -- Flux reconciliation overrides specifically for the Istio Operator Package
#    flux: {}

    # -- Values to passthrough to the istio-operator chart: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-operator.git
#    values: {}

    # -- Post Renderers.  See docs/postrenders.md
#    postRenderers: []

gatekeeper:
  enabled: false
  values:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    violations:
      allowedDockerRegistries:
        match:
          excludedNamespaces:
          - kube-system
          - istio-system
          - default

kiali:
  enabled: false

jaeger:
  enabled: false

logging:
  enabled: false

fluentbit:
  enabled: false

clusterAuditor:
  enabled: false

monitoring:
  enabled: false

eckoperator:
  enabled: false

twistlock:
  enabled: false
