hostname: bigbang.dev

istio:
  enabled: false

istiooperators:
  # -- Toggle deployment of Istio Operator.
#- enabled: false
#  revision: ""
#  git:
#    repo: https://github.com/danehans/istio-operator.git
#    path: "./chart"
#    tag: ""
#    branch: revision
- enabled: false
  revision: "1-9-7"
  git:
    repo: https://github.com/danehans/istio-operator.git
    path: "./chart"
    tag: ""
    branch: revision

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

gatekeeper:
  enabled: false
  values:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    violations:
      allowedDockerRegistries:
        match:
          excludedNamespaces:
          - kube-system
          - istio-system
          - default

kiali:
  enabled: false

jaeger:
  enabled: false

logging:
  enabled: false

fluentbit:
  enabled: false

clusterAuditor:
  enabled: false

monitoring:
  enabled: false

eckoperator:
  enabled: false

twistlock:
  enabled: false
