hostname: bigbang.dev

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

gatekeeper:
  values:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    violations:
      allowedDockerRegistries:
        match:
          excludedNamespaces:
          - kube-system
          - istio-system
          - default

kiali:
  enabled: false

jaeger:
  enabled: false

logging:
  enabled: false

fluentbit:
  enabled: false

clusterAuditor:
  enabled: false

monitoring:
  enabled: false

eckoperator:
  enabled: false

twistlock:
  enabled: false
