hostname: bigbang.dev

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

logging:
  enabled: true
  values:
    elasticsearch:
      master:
        count: 1
        persistence:
          size: 5Gi
        resources:
          requests:
            cpu: .5
          limits: {}
      data:
        count: 1
        persistence:
          size: 5Gi
        resources:
          requests:
            cpu: .5
          limits: {}

fluentbit:
  values:
    securityContext:
      privileged: true

istio:
  enabled: true
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane.git
    tag: null
    #tag: 1.8.4-bb.6
    branch: "23-IstioCP-1.10.1"
  # See https://repo1.dso.mil/platform-one/big-bang/customers/template/-/issues/13
  ingress:
    key: ""
    cert: ""
  values:
    hub: registry1.dso.mil/ironbank/opensource/istio
    tag: 1.10.3
  values:
    kiali:
    image:
      name: kiali
      hub: registry1.dso.mil/ironbank/opensource/kiali/kiali
      tag: v1.37.0
      dashboard:
        auth:
          strategy: "anonymous"
    cni:
    image:
      name: install-cni
      hub: registry1.dso.mil/ironbank/opensource/istio/install-cni
      tag: 1.10.3

clusterAuditor:
  enabled: true
  values:
    resources:
      requests:
        cpu: 100m
        memory: .5Gi
      limits: {}

monitoring:
  enabled: true
  values:
    alertmanager:
      alertmanagerSpec:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits: {}
    prometheusOperator:
      resources:
        requests:
          cpu: 250m
          memory: 400Mi
        limits: {}
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits: {}
    grafana:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits: {}
    kubeStateMetrics:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits: {}
    nodeExporter:
      resources:
        requests:
          cpu: 100m
          memory: 30Mi
        limits: {}

gatekeeper:
  enabled: true
  git:
    tag: 3.5.1-bb.5
  values:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits: {}

twistlock:
  enabled: false
  values:
    console:
      persistence:
        size: 5Gi

istiooperator:
  enabled: true
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-operator.git
    #tag: 1.8.4-bb.2
    tag: null
    branch: "2-IstioOp-1.10.1"
  values:
    hub: registry1.dso.mil/ironbank/opensource/istio
    tag: 1.10.3

addons:
  authservice:
    enabled: true
    values:
      replicaCount: 3
