hostname: bigbang.dev

#flux:
#  interval: 1m
#  rollback:
#    cleanupOnFail: false

istio:
  enabled: true
  git:
    repo: https://github.com/danehans/istio-controlplane.git
    path: "./chart"
    tag: null
    branch: revision_support
    ingressGateways:
      public-ingressgateway:
        type: "LoadBalancer"
        kubernetesResourceSpec:
          service:
            externalIPs:
            - 34.94.201.245

istiooperator:
  enabled: true
  git:
    repo: https://github.com/danehans/istio-operator.git
    path: "./chart"
    tag: null
    branch: revision

istios:
  default:
    enabled: false
    git:
      repo: https://github.com/danehans/istio-controlplane.git
      path: "./chart"
      tag: null
      branch: revision_support
    ingressGateways:
      public-ingressgateway:
        type: "LoadBalancer"
        kubernetesResourceSpec:
          service:
            externalIPs:
            - 34.94.201.245
    flux: {}
    values: {}
    postRenderers: []
  1-11-1:
    enabled: false
    revision: 1-11-1
    git:
      repo: https://github.com/danehans/istio-controlplane.git
      path: "./chart"
      tag: null
      branch: revision_support
    ingressGateways:
      public-ingressgateway:
        type: "LoadBalancer"
        kubernetesResourceSpec:
          service:
            externalIPs:
            - 34.94.201.245
    flux: {}
    values:
      tag: 1.11.1
    postRenderers: []

istiooperators:
  default:
    enabled: false
    git:
      repo: https://github.com/danehans/istio-operator.git
      path: "./chart"
      tag: null
      branch: revision
    flux: {}
    values: {}
    postRenderers: []
  1-11-1:
    enabled: false
    revision: 1-11-1
    git:
      repo: https://github.com/danehans/istio-operator.git
      path: "./chart"
      tag: null
      branch: revision
    flux: {}
    values:
      tag: 1.11.1
    postRenderers: []

istiogateway:
  enabled: false

gatekeeper:
  enabled: false
  values:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    violations:
      allowedDockerRegistries:
        match:
          excludedNamespaces:
          - kube-system
          - istio-system
          - default

kiali:
  enabled: false

jaeger:
  enabled: false

logging:
  enabled: false

fluentbit:
  enabled: false

clusterAuditor:
  enabled: false

monitoring:
  enabled: false

eckoperator:
  enabled: false

twistlock:
  enabled: false
