hostname: bigbang.dev

flux:
  interval: 15s
#  rollback:
#    cleanupOnFail: false

istio:
  enabled: false
  git:
    repo: https://github.com/danehans/istio-controlplane.git
    path: "./chart"
    tag: null
    branch: revision_support
    ingressGateways:
      public-ingressgateway:
        type: "LoadBalancer"
        kubernetesResourceSpec: {}
#          service:
#            externalIPs:
#            - 34.102.16.247
#  values: {}
  values:
    tag: 1.11.1

istiooperator:
  enabled: false
  git:
    repo: https://github.com/danehans/istio-operator.git
    path: "./chart"
    tag: null
    branch: revision
  values:
    tag: 1.11.1

istios:
  default:
    enabled: false
    git:
      repo: https://github.com/danehans/istio-controlplane.git
      path: "./chart"
      tag: null
      branch: revision_support
    ingressGateways:
      public-ingressgateway:
        type: "LoadBalancer"
        kubernetesResourceSpec: {}
#          service:
#            externalIPs:
#            - 34.102.16.247
    flux: {}
#    values: {}
    values:
      tag: 1.11.1
    postRenderers: []
  1-11-2:
    enabled: true
    revision: 1-11-2
    git:
      repo: https://github.com/danehans/istio-controlplane.git
      path: "./chart"
      tag: null
      branch: revision_support
    ingressGateways:
      public-ingressgateway:
        type: "LoadBalancer"
        kubernetesResourceSpec: {}
    flux: {}
    values:
      tag: 1.11.2
    postRenderers: []

istiooperators:
  default:
    enabled: false
    git:
      repo: https://github.com/danehans/istio-operator.git
      path: "./chart"
      tag: null
      branch: revision
    flux: {}
#    values: {}
    values:
      tag: 1.11.1
    postRenderers: []
  1-11-2:
    enabled: true
    revision: 1-11-2
    git:
      repo: https://github.com/danehans/istio-operator.git
      path: "./chart"
      tag: null
      branch: revision
    flux: {}
    values:
      tag: 1.11.2
    postRenderers: []

istiogateway:
  enabled: true

gatekeeper:
  enabled: true
  values:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    violations:
      allowedDockerRegistries:
        match:
          excludedNamespaces:
          - kube-system
          - istio-system
          - default

kiali:
  enabled: true

jaeger:
  enabled: true

logging:
  enabled: true
  values:
    elasticsearch:
      master:
        count: 1
        persistence:
          size: 5Gi
        resources:
          requests:
            cpu: .5
          limits:
            cpu: 2
      data:
        count: 1
        persistence:
          size: 5Gi
        resources:
          requests:
            cpu: .5
          limits:
            cpu: 2

monitoring:
  enabled: true
  values:
    alertmanager:
      alertmanagerSpec:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
#    prometheusOperator:
#      resources:
#        requests:
#          cpu: 250m
#          memory: 400Mi
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 2
    grafana:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    kubeStateMetrics:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
    nodeExporter:
      resources:
        requests:
          cpu: 100m
          memory: 30Mi

eckoperator:
  enabled: false

twistlock:
  enabled: false

fluentbit:
  enabled: true
  values:
    securityContext:
      privileged: true

clusterAuditor:
  enabled: true
  values:
    resources:
      requests:
        cpu: 100m
        memory: .5Gi

#addons:
#  argocd:
#    enabled: true
