hostname: bigbang.dev

#networkPolicies:
#  enabled: false

flux:
  interval: 5s
  rollback:
    cleanupOnFail: false

istiooperator:
  enabled: true
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-operator.git
    path: "./chart"
    tag: null
    branch: main
  values:
    tag: 1.11.1

istio:
  enabled: true
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane.git
    path: "./chart"
    tag: null
    branch: issue_54
  ingressGateways:
    public-ingressgateway:
      type: "LoadBalancer"
      kubernetesResourceSpec: { }
  values:
    tag: 1.11.1
  controlplanes:
    default:
      enabled: false
      git:
        repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane.git
        path: "./chart"
        tag: null
        branch: issue_54
      ingressGateways:
        public-ingressgateway:
          type: "LoadBalancer"
          kubernetesResourceSpec: { }
      flux: { }
      values:
        tag: 1.11.1
      postRenderers: [ ]
    1-11-2:
      enabled: false
      revision: 1-11-2
      git:
        repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane.git
        path: "./chart"
        tag: null
        branch: issue_54
      ingressGateways:
        public-ingressgateway:
          type: "LoadBalancer"
          kubernetesResourceSpec: { }
      flux: { }
      values: { }
      postRenderers: [ ]
  operators:
    default:
      enabled: false
      git:
        repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-operator.git
        path: "./chart"
        tag: null
        branch: main
      values:
        tag: 1.11.1
      flux: { }
      postRenderers: []
    1-11-2:
      enabled: false
      revision: 1-11-2
      git:
        repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-operator.git
        path: "./chart"
        tag: null
        branch: main
      values: { }
      flux: { }
      postRenderers: []

gatekeeper:
  enabled: true
  values:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    violations:
      allowedDockerRegistries:
        match:
          excludedNamespaces:
          - kube-system
          - istio-system
          - default

kiali:
  enabled: true

jaeger:
  enabled: true

logging:
  enabled: true
  values:
    elasticsearch:
      master:
        count: 1
        persistence:
          size: 5Gi
        resources:
          requests:
            cpu: .5
          limits:
            cpu: 2
      data:
        count: 1
        persistence:
          size: 5Gi
        resources:
          requests:
            cpu: .5
          limits:
            cpu: 2

fluentbit:
  enabled: false

clusterAuditor:
  enabled: false

monitoring:
  enabled: true
  values:
    alertmanager:
      alertmanagerSpec:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
#    prometheusOperator:
#      resources:
#        requests:
#          cpu: 250m
#          memory: 400Mi
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 2
    grafana:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    kubeStateMetrics:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
    nodeExporter:
      resources:
        requests:
          cpu: 100m
          memory: 30Mi

eckoperator:
  enabled: false

twistlock:
  enabled: false
