# When updating the version of BigBang, make sure to update
#   both the bases reference and the GitRepository reference
bases:
- git::https://github.com/danehans/big-bang.git//base?ref=7cdaac5c41c2b8340e51d35a5f6b8b6c4276fd09
configMapGenerator:
  - name: common
    behavior: merge
    files:
      - values.yaml=configmap.yaml
patchesStrategicMerge:
- secrets.enc.yaml
- |-
  apiVersion: source.toolkit.fluxcd.io/v1beta1
  kind: GitRepository
  metadata:
    name: bigbang
  spec:
    ref:
      $patch: replace
      tag: ""
      branch: operator_map
