apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:wqaIp8VHu1PmPS8yW1hF2VIN0cb/1UyN2oV1j6dl/T07GkXC86SzU6U1KhJeX8n7hjgdBxXScQu4vrhc/JHJlxvGhTe9cJXsrsmCgUzqBMu02xmrWgkwAzDk/VckHtHLcioxZ6XIoNkHxNNA9yzCgwnfQL/VYgSGmhbLwg==,iv:pq/CBeopmy2d2ivwGbcxyFWF/SL3Wr+ohz/PoKBUw6I=,tag:IwqP+N1sxyCp+yrR/BQk9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-21T22:34:24Z"
    mac: ENC[AES256_GCM,data:LenUbYhVmK/6VrpKpkWuIEBplfFsxnTHY6SrRIGSzYidsHycrelEGSBPIP8AO7jR4WKHKevAAM8N1CW4P90pw48hoW6HU9p7uY42TfElzZMo2I7EXEcIQ1u9RU9PtRxhMDFZHrmwo7HChEwSCswfLRNsdw1jXtfJqmHjKBtugDc=,iv:ewo0Xk8tiPJtVX2z+aleM3HN7i3SPbEHWptEYu5JP6M=,tag:2sZVqx8Uw6+Ra02aQAYjqQ==,type:str]
    pgp:
        - created_at: "2021-07-21T22:34:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3sO6Y7qGXAdAQ//fNQz9ij2sMpK5r0y8t9qVzzz0uiQz9CsRUNbqMY5LpF7
            TlyVaDRl1n1zf/yZfukV2v2JacV5s4CkAk5a2cCx1qwDfNAoOKt89Cfx/nG3vBmF
            H+ML7AUu0e7FboBtxZK3AGr/PXIAF3qEdPDUjKKnNPoBrpYcsKjZDwQ+YTLIKAtf
            vfaFKbE7FjqY1+1xwj+SwYPn50lsczgYo/6LM7EiG+4BwFCPjBeNDPINYCicH36F
            1NQ1VqyR59PumRca2JuX0BM33J0vOgF8EjxRq9Fs60TIqAJtDAB02KpXeFUJMRLr
            KUAWITjF7A2Ok5LhQE9yA/PczBqwDBP9BBfVdP0uPY2eNQAVxH39Gv9cvqGa592K
            KqigiwaHGLIVAsP4ZSNSdvOUB5eMQdW7d/ikqC6SWj4pELA9W/LIaOqS8eYEtz8c
            1Aps4EP27pSAB5hCazRfoPNwarDhkk6QLcK3sdCwz98UPr9HXIOZfudV7jBUAL7L
            JG9IL9+LbMGAXGyLASAPB4NXVMa6fv1wTrhoCx+yGrVaY75ANOs6/8U4r1wNAJAG
            GD/PeKdZ5UujsKHH1fI8/TaUuAbg2tLe92aCWfHAnj57xgmkHpkrn8ajnnyJCJ3H
            kJzt4LmACDTB2I7BE1fd5Qg6TtXhcarmyKuRB5uTqcJBpQDdML4NNweMFUIU73PS
            XgE2S34X9VS8vIXSDSnW26oHBXQThyNmmXsFpSPE8auAfDanY6Id+lo+otH4JmTu
            yqKBLXVf5pmARTcATLJVtbbWSKbzfzQ6VMqMHFpIOA0rMSdXUSI96q5XXsLNqno=
            =9T2+
            -----END PGP MESSAGE-----
          fp: 15EA2E820D77333EF15E70D6BD5E83C90589EC57
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
