apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:D+SZDfarF3qgwYpFpfPaUtUa8956OWWBNxUAxmQibbfQJVdSbwlZ4yHB07bWnc/Do5PuCyqKPmRzIN+tuvdmuUOf4Uni1GA1sfiMydYkFZJ2wSst9wkFLFU/n7diY6B89bXxPk/iLkmg4xsEfqcc3KSgYeLoVIxEPrHf/5kcJHujcw==,iv:7l8/NPQnqpcytZM628p9cerupQrSs8P0NFvRygTvk5E=,tag:nZK/Js4+eebMXoE72ROdow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-13T20:42:39Z"
    mac: ENC[AES256_GCM,data:+PN5jyNTDQJRyIIjG0pKt8UkD0JkjOceWw5/xDmasX21ny+2SmSgT09uYHSeIxhk+Mejgj525dkPPR4MCLFxDSF8NCgF3Y5iCK3+/h5G3KsPLy1rB8XAREdycBI4a1iJNWnveeDX6++WU3ySCSlt5/kEomnzD5lMOY1BY4EUl8Q=,iv:CXnwcLW0nopUk5Mr9Pru6tUr6TEw4X8gmjdmD0nnm24=,tag:k1gNE77LWqLDgk2tnhxzSg==,type:str]
    pgp:
        - created_at: "2021-07-13T20:37:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzOIES1fIlhkAQ//RiQSx39gBMer3BCX5ykW/+W9cqHcaDqSL27rv9YhJR5T
            ipLraCy3uvAruhAaEx4Lxq4YfycOb+8UK6mFy5mttJdkCbf1tcD4b8S8xLqRJIj9
            qCbrBZ5dNnebzAzm9MKPfdCxAx90DrSBs34+3tUe4apEv/Km+qmZkafiRTShDomf
            1//KvDVxD00HOHemwtcYQ2dPqAdmWWYb89NM8Pa/gCrqYajs5V2NdFxvHKPh+By+
            6/NzCYshe3WetbgFZa9sRNhpJy2Eq/okpuaoqxPZQq1/hSx2Hwkt85Ec2hRca8yY
            3zoXOd+hPpVh4mhIluzHfIups1kWZjCST8q+HFCvILaEgEnJxa2rzHqDw4NByLQ8
            +osrd+uh55yeogF7HO8OFspbvtlr2orCvxFsLIPvYyJEBOPgg/4AvypW7MUkLE10
            axEJiin45pt0Ky53DLwEoDxZ2yNjnqRznNvYDySZYBk/PlZ6uHXoIfWVud5nhdGY
            LQ0h9+aUU35BVynTjSd8YUuzeRWUmbsh4sBdrEwDTGfsPe/OuxvKmYDcFhFihtRY
            gN69q0Ea4m0h4ibUNjkQ5EiUdGMR9cYifBtP/bjlc9r9USrPJvIBVHUBH7TV6png
            9u3yT0iAzevZ5l5i2qCH5+sabZh/rvuBfkbRC/WkptEjIYEMlHmT1GV5lPTQI7rS
            XgFja3GL/fPPbiVKPbcaolDEUS1l30fwrvTcqYE0k/oJ2dAYfaJLcIlIjOg2DFrP
            OwjkhG4MRv5/FxNM53FCnQtJ+LlibAO9jeZVGfSjfFpjeOiFhkSz7iubgmW6juo=
            =MYWA
            -----END PGP MESSAGE-----
          fp: 3868B679AE3DA1A8E4A9DA553CFA81BA94ECB7E3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
